version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8082:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - GOOGLE_SHEETS_JSON_BASE64=${GOOGLE_SHEETS_JSON_BASE64}
      - GOOGLE_SHEETS_ISRC_NAME=${GOOGLE_SHEETS_ISRC_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - XMPLAYLIST_BASE_URL=${XMPLAYLIST_BASE_URL}
    depends_on:
      - mongo
    ports:
      - "8001:8000"  # Map host port 8001 to container port 8000
    networks:
      - app-network
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=sirius_tracker
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  cron:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - XMPLAYLIST_BASE_URL=${XMPLAYLIST_BASE_URL}
    volumes:
      - ./scripts/log.txt:/app/log.txt
    depends_on:
      - mongo
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data: